with open('numar.txt','r') as f:
    a=f.readline()
n1='1*'+ a + '=' + str(1*int(a))
n2='2*'+ a + '=' + str(2*int(a))
n3='3*'+ a + '=' + str(3*int(a))
n4='4*'+ a + '=' + str(4*int(a))
n5='5*'+ a + '=' + str(5*int(a))
n6='6*'+ a + '=' + str(6*int(a))
n7='7*'+ a + '=' + str(7*int(a))
n8='8*'+ a + '=' + str(8*int(a))
n9='9*'+ a + '=' + str(9*int(a))
n10='10*'+ a + '=' + str(10*int(a))
with open('inmultire.txt','w') as f:
    f.write(str(n1))
    f.write('\n')
    f.write(str(n2))
    f.write('\n')
    f.write(str(n3))
    f.write('\n')
    f.write(str(n4))
    f.write('\n')
    f.write(str(n5))
    f.write('\n')
    f.write(str(n6))
    f.write('\n')
    f.write(str(n7))
    f.write('\n')
    f.write(str(n8))
    f.write('\n')
    f.write(str(n9))
    f.write('\n')
    f.write(str(n10))